Homework #4: Two counters
Fumuran/KIS_ReactJS_Fall2021 pull request #1
Opened 2021-10-06 13:17 UTC by Overcastan

Author: Khmuro Andrew

2021-10-09 16:24 UTC, dshuran requested changes

2021-10-09 16:24 UTC, dshuran commented on src/App.js
> +    <div className="App" style={background}>
Кажется, тут нет необходимости, чтобы задавать стили через атрибут style. Лучше делать это через CSS-классы. style же можно рассматривать как одну из последних инстанций, если очень нужно что-то переопределить

2021-10-09 16:24 UTC, dshuran commented on src/App.js
> +            <Counter counterNumber={"first"} start={0}/>
Если хотим передать статичную строку, то фигурные скобки вокруг неё не нужны.

2021-10-09 16:24 UTC, dshuran commented on src/Counter.jsx
> +        this.setState((prevState) => {
Начальное состояние лучше задать в конструкторе. Можно не через setState, а просто присвоить объект

2021-10-09 16:24 UTC, dshuran commented on src/Counter.jsx
> +        this.setState((prevState) => {
Увидел, что это и так делается. Тогда вообще непонятно, зачем нужен этот кусок кода. Все исходные значения можно задать в конструкторе

2021-10-09 16:24 UTC, dshuran commented on src/Counter.jsx
> +            counter: 10
Свойство counter не используется при рендере и не нужно в state. Его можно вынести просто как отдельное поле класса.

2021-10-09 16:24 UTC, dshuran commented on src/Counter.jsx
> +                if (prevState.counter === 0) {
При возникновении этого условия нужно остановить счётчик (clearInterval(this.timerId);). А то он так и будет вечно работать, и мы будем возвращать одно и то же значение. Поздравляю со знакомством с утечками памяти :)

2021-10-09 16:24 UTC, dshuran commented on src/Counter.jsx
> +            <div style={counterStyle}>
Аналогично, стили лучше задавать через CSS-классы

2021-10-11 09:46 UTC, Fumuran commented on src/Counter.jsx
> +            counter: 10
Вынес counter в поле класса, но возникла странная проблема: counter через каждую секунду уменьшается сразу на 2, а не на 1, даже если я создаю только один экземпляр класса Counter, будто бы декремент для этой переменной вызывается два раза. Только мне так и не удалось понять, почему так происходит.

2021-10-14 05:43 UTC, dshuran approved these changes

2021-10-14 05:43 UTC, merged